// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:main.Todo):Promise<void>;

export function CreateMarkdownFile(arg1:string,arg2:string):Promise<string>;

export function DeleteCodeFile(arg1:string):Promise<void>;

export function DeleteCodeFolder(arg1:string):Promise<void>;

export function DeleteMarkdownFile(arg1:string):Promise<void>;

export function DeleteMarkdownFolder(arg1:string):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetCodeFolders():Promise<Array<main.CodeFolder>>;

export function GetConfigDir():Promise<string>;

export function GetTodos():Promise<Array<main.Todo>>;

export function ImportCodeFile(arg1:string,arg2:string):Promise<string>;

export function ImportMarkdownFile(arg1:string,arg2:string):Promise<string>;

export function LoadBookmarks():Promise<string>;

export function LoadCodeTemplates():Promise<string>;

export function LoadMarkdownFiles():Promise<string>;

export function OpenDataFolder():Promise<string>;

export function OpenWithDefaultApp(arg1:string):Promise<void>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveBookmarks(arg1:string):Promise<void>;

export function SaveCodeTemplates(arg1:string):Promise<void>;

export function SaveMarkdownContent(arg1:string,arg2:string):Promise<void>;

export function SaveMarkdownFiles(arg1:string):Promise<void>;

export function SelectCodeFile():Promise<string>;

export function SelectMarkdownFile():Promise<string>;

export function SyncCodeTemplates():Promise<void>;

export function SyncMarkdownFiles():Promise<void>;

export function UpdateTodo(arg1:main.Todo):Promise<void>;
