// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigDir():Promise<string>;

export function LoadBookmarks():Promise<string>;

export function SaveBookmarks(arg1:string):Promise<void>;
