// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function LoadBookmarks() {
  return window['go']['main']['App']['LoadBookmarks']();
}

export function SaveBookmarks(arg1) {
  return window['go']['main']['App']['SaveBookmarks'](arg1);
}
