// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function CreateMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['CreateMarkdownFile'](arg1, arg2);
}

export function DeleteCodeFile(arg1) {
  return window['go']['main']['App']['DeleteCodeFile'](arg1);
}

export function DeleteCodeFolder(arg1) {
  return window['go']['main']['App']['DeleteCodeFolder'](arg1);
}

export function DeleteMarkdownFile(arg1) {
  return window['go']['main']['App']['DeleteMarkdownFile'](arg1);
}

export function DeleteMarkdownFolder(arg1) {
  return window['go']['main']['App']['DeleteMarkdownFolder'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetCodeFolders() {
  return window['go']['main']['App']['GetCodeFolders']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function ImportCodeFile(arg1, arg2) {
  return window['go']['main']['App']['ImportCodeFile'](arg1, arg2);
}

export function ImportMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['ImportMarkdownFile'](arg1, arg2);
}

export function LoadBookmarks() {
  return window['go']['main']['App']['LoadBookmarks']();
}

export function LoadCodeTemplates() {
  return window['go']['main']['App']['LoadCodeTemplates']();
}

export function LoadMarkdownFiles() {
  return window['go']['main']['App']['LoadMarkdownFiles']();
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenWithDefaultApp'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function SaveBookmarks(arg1) {
  return window['go']['main']['App']['SaveBookmarks'](arg1);
}

export function SaveCodeTemplates(arg1) {
  return window['go']['main']['App']['SaveCodeTemplates'](arg1);
}

export function SaveMarkdownContent(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdownContent'](arg1, arg2);
}

export function SaveMarkdownFiles(arg1) {
  return window['go']['main']['App']['SaveMarkdownFiles'](arg1);
}

export function SelectCodeFile() {
  return window['go']['main']['App']['SelectCodeFile']();
}

export function SelectMarkdownFile() {
  return window['go']['main']['App']['SelectMarkdownFile']();
}

export function SyncCodeTemplates() {
  return window['go']['main']['App']['SyncCodeTemplates']();
}

export function SyncMarkdownFiles() {
  return window['go']['main']['App']['SyncMarkdownFiles']();
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}
