// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:main.Todo):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetConfigDir():Promise<string>;

export function GetTodos():Promise<Array<main.Todo>>;

export function LoadBookmarks():Promise<string>;

export function SaveBookmarks(arg1:string):Promise<void>;
